# -*- coding: utf-8 -*-
#
# Copyright (C) 2022 CESNET.
#
# oarepo-versions-tests is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

name: cron wf wrapper

on:
  schedule:
    # every day at 6:39 GMT
    - cron: '39 6 * * *'
    # every sat. at 6:39 GMT
    #- cron: '39 6 * * 6'
    # debug run
    #- cron: '4 14 * * *'
  workflow_dispatch:

jobs:
  cron-wf-trig:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        branch: [ 'main' ]
    steps:
      - name: Trig workflow in ${{ matrix.branch }} br.
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: 73216393
          token: ${{ secrets.OAREPO_BOT }}
          ref: ${{ matrix.branch }}
