name: Dispatch

on:
  workflow_dispatch:
    inputs:
      oarepo:
        description: OARepo version (11, 12, ...)
        required: true
        default: 11

jobs:
  call:
    uses: ./.github/workflows/check_versions.yaml
    with:
      oarepo: ${{ github.event.inputs.oarepo }}
