name: Test

on:
  workflow_call:
    inputs:
      oarepo:
        description: OARepo version (11, 12, ...)
        required: true
        default: 11
        type: string
  workflow_dispatch:
    inputs:
      oarepo:
        description: OARepo version (11, 12, ...)
        required: true
        default: 11

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #python-version: [ "3.9", "3.10" ]
        python-version: [ "3.10" ]
        oarepo-library: [ "oarepo/oarepo-runtime", "oarepo/oarepo-vocabularies" ]
    env:
      OAREPO_VERSION: ${{ github.event.inputs.oarepo }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip
        uses: actions/cache@v3
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      - name: artifact test 1
        run: |
          REPO="${{ matrix.oarepo-library }}"
          BASE_URL="https://api.github.com/repos/$REPO"
          BR="main"
          function api_get(){
            URL=${1:-$BASE_URL}
            shift
            curl -s -XGET -H "Accept: application/vnd.github.v3+json" -H "authorization: Bearer ${{ secrets.INTEGRATION_TEST }}" -d '{"ref":"'$BR'"}' "$URL" $@
          }
          echo "REPO=$REPO:  (BASE_URL=$BASE_URL)"
          api_get "$BASE_URL/actions/runs"

#      - name: Download artifacts
#        uses: actions/Download-artifact@v3
#        with:
#          name: dist
#          path: dist

#      - name: Archive production artifacts
#        uses: actions/upload-artifact@v3
#        with:
#          name: requirements.txt
#          path: requirements.txt
